# Generated by Django 5.1.6 on 2025-02-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=255)),
                ('execution_date', models.DateTimeField(auto_now_add=True)),
                ('return_code', models.IntegerField()),
                ('output', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
