# Generated by Django 5.1.6 on 2025-02-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_executionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrecord',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
